### ISSUE TITLE
Add .gitignore file

### ISSUE THREAD

**Issue by feedbacker1991** [ashishkrishan1995/Desyrel-Font#2]
.idea/ and other developer specific and ide specfic files should be ignored by git. Adding a .gitignore file hence is a must.

**Comment by feedbacker1991** [comment]
I want to work on this one.

**Comment by ashishkrishan1995** [comment]
sure go aheah

**Comment by feedbacker1991** [comment]
Can you add hacktoberfest as a label to it as well :D ?

**Comment by ashishkrishan1995** [comment]
Done

**Comment by feedbacker1991** [comment]
Can you also remove the ignored files yourself and push a commit again so we can see the updated code in the repository as well.

And in case you would want to help me in correcting my repositories . Here is a link to them

https://github.com/raul1991
